version: '3.7'


services:
  postgres:
    container_name: psql
    build: ./postgres
    environment:
      - POSTGRES_MULTIPLE_DATABASES=fastapi,keycloak
      - POSTGRES_USER=octa
      - POSTGRES_PASSWORD=octa
    volumes:
      - ./postgres/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"


  fastapi:
    container_name: fastapi
    build: ./fastapi
    restart: always
    environment:
      - MONGO_USERNAME=octa
      - MONGO_PASSWORD=octa
      - MONGO_HOST=mongo
      - MONGO_DATABASE=OctaMoniotr
      - CLIENT=octa-auth
      - CLIENT_SECRET=NJqY164xsUTzDfJKn96VJ60iNU0GguAf
      - DOMAIN=www.octamonitor.com
      - ADMIN_DOMAIN=admin.octamonitor.com
      - REALM=octa
    ports:
      - "8001:8001"
    extra_hosts:
      - "auth.octamonitor.com:192.168.43.156"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: "on-failure"

  keycloak:
    build: ./keycloak
    container_name: Keycloak
    restart: "unless-stopped"
    environment: 
      - KEYCLOAK_USER=octa
      - KEYCLOAK_PASSWORD=octa
      - KEYCLOAK_IMPORT=/tmp/import-realm.json
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=https://auth.octamonitor.com/auth
      - KEYCLOAK_HTTP_PORT=443
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=octa
      - DB_SCHEMA=public
      - DB_PASSWORD=octa
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import",
      "-Dkeycloak.migration.provider=dir",
      "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config",
      "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    volumes:
      - realm-config:/opt/jboss/keycloak/realm-config
      - keycloak-db:/opt/jboss/keycloak/standalone/dat
    ports:
        - "8080:8080"


  mongo:
    build: ./mongodb
    container_name: "mongodb"
    restart: unless-stopped
    command: mongod --auth
    # volumes:
    #   - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - 27018:27018
 
  


# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge


volumes:
  realm-config:
  keycloak-db:
  # mongodb:
  postgres_data:
      driver: local